import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const MANAGED_PREFIX = '<!-- Generated by Buildr.';
export const FRONTMATTER_BOUNDARY = '---';
export const SKILL_CONTRIBUTION_MARKER = /^<!-- buildr:skill-contributions ([a-z][a-z0-9-]*) -->$/gm;

export function normalizeRelativePath(input) {
  const normalized = path.normalize(input).replace(/^\.\//, '');
  if (path.isAbsolute(normalized) || normalized === '..' || normalized.startsWith(`..${path.sep}`)) {
    throw new Error(`Path must stay inside repository: ${input}`);
  }
  return normalized;
}


export function productRoot() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
}

export function packageRoot() {
  return path.join(productRoot(), 'package');
}

export function resolveSkillScope(repoRoot, scopeInput) {
  const scope = normalizeRelativePath(scopeInput);
  const parts = scope === '.' ? ['.'] : scope.split(path.sep);
  let organizationRoot;
  let projectRoot = null;
  if (parts[0] === '.') {
    organizationRoot = repoRoot;
  } else if (parts[0] === 'projects') {
    if (parts.length !== 2) throw new Error(`Project scope must be projects/<project>: ${scopeInput}`);
    organizationRoot = repoRoot;
    projectRoot = path.join(repoRoot, 'projects', parts[1]);
  } else {
    throw new Error(`Unsupported scope. Use . or projects/<project>: ${scopeInput}`);
  }
  ensureDirectory(organizationRoot, `Organization scope does not exist: ${path.relative(repoRoot, organizationRoot)}`);
  if (projectRoot) {
    ensureDirectory(projectRoot, `Project scope does not exist: ${path.relative(repoRoot, projectRoot)}`);
  }
  return { scope, organizationRoot, projectRoot };
}

export function ensureDirectory(dir, message) {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    throw new Error(message);
  }
}

export function ensureFile(file, message) {
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) {
    throw new Error(message);
  }
}


export function unquoteYamlScalar(value) {
  const trimmed = value.trim();
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

export function parseSkillFrontmatterName(skillFile) {
  return parseSkillFrontmatterNameFromContent(fs.readFileSync(skillFile, 'utf8'), skillFile);
}

export function parseSkillFrontmatterNameFromContent(content, label) {
  const lines = content.split(/\r?\n/);
  if (lines[0] !== FRONTMATTER_BOUNDARY) {
    throw new Error(`SKILL.md must start with YAML frontmatter: ${label}`);
  }
  const endIndex = lines.findIndex((line, index) => index > 0 && line === FRONTMATTER_BOUNDARY);
  if (endIndex === -1) {
    throw new Error(`SKILL.md frontmatter is not closed: ${label}`);
  }
  for (const rawLine of lines.slice(1, endIndex)) {
    const match = rawLine.trim().match(/^name:\s*(.+)$/);
    if (match) return unquoteYamlScalar(match[1]);
  }
  throw new Error(`SKILL.md frontmatter must declare name: ${label}`);
}
