set -euo pipefail

product_root="${product_root:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
buildr="$product_root/tools/buildr"
main_worktree="$(git -C "$product_root" worktree list --porcelain | sed -n 's/^worktree //p' | head -n 1)"
main_status_before="$(git -C "$main_worktree" status --porcelain=v1 --untracked-files=all)"
tmp="$(mktemp -d)"
remote_parent="$(mktemp -d)"
remote_repo="$remote_parent/api.git"
remote_seed="$(mktemp -d)"
project_repo="$(mktemp -d)"
local_repo="$(mktemp -d)"
npm_pack_dir="$(mktemp -d)"
npm_prefix="$(mktemp -d)"
npm_workspace="$(mktemp -d)"
npm_skill_workspace="$(mktemp -d)"
skill_install_target="$(mktemp -d)"
remote_skill_dir="$(mktemp -d)"
reconcile_tmp="$(mktemp -d)"
remote_skill_pid=""
current_section=""
section_started_at=""

now_ms() {
  node -e 'process.stdout.write(String(Date.now()))'
}

finish_section() {
  local status="${1:-0}"
  local finished_at duration_ms result
  if [[ -z "$current_section" ]]; then
    return
  fi
  finished_at="$(now_ms)"
  duration_ms="$((finished_at - section_started_at))"
  result="passed"
  if [[ "$status" -ne 0 ]]; then
    result="failed"
  fi
  printf '[verify-mvp] completed: %s (%s ms)\n' "$current_section" "$duration_ms"
  if [[ -n "${BUILDR_MVP_TIMING_FILE:-}" ]]; then
    printf '%s\t%s\t%s\t%s\n' "$current_section" "$result" "$status" "$duration_ms" >> "$BUILDR_MVP_TIMING_FILE"
  fi
  current_section=""
}

cleanup() {
  local status=$?
  finish_section "$status"
  if [[ -n "$remote_skill_pid" ]]; then
    kill "$remote_skill_pid" >/dev/null 2>&1 || true
    wait "$remote_skill_pid" 2>/dev/null || true
  fi
  rm -rf "$tmp" "$remote_parent" "$remote_seed" "$project_repo" "$local_repo" "$npm_pack_dir" "$npm_prefix" "$npm_workspace" "$npm_skill_workspace" "$skill_install_target" "$remote_skill_dir" "$reconcile_tmp"
}
trap cleanup EXIT

section() {
  finish_section 0
  current_section="$1"
  section_started_at="$(now_ms)"
  printf '\n[verify-mvp] %s\n' "$1"
}

assert_compact_claude_bridge() {
  local file="$1"
  test -f "$file"
  grep -q '^<!-- BEGIN Buildr managed Claude Code rules bridge; type: reference; source: AGENTS.md -->$' "$file"
  grep -q '^@AGENTS.md$' "$file"
  grep -q '^<!-- END Buildr managed Claude Code rules bridge -->$' "$file"

  for old_marker in \
    'hash:' \
    'Generated by Buildr. Source: rules render claude-code' \
    'Buildr source hash:' \
    'Buildr 管理区块' \
    '规则来自同目录 AGENTS.md'; do
    if grep -Fq "$old_marker" "$file"; then
      echo "CLAUDE.md contains verbose legacy marker: $old_marker" >&2
      exit 1
    fi
  done
}

section "准备临时依赖"

git init --bare "$remote_repo" >/dev/null
git -C "$remote_seed" init -b main >/dev/null
git -C "$remote_seed" config user.email buildr@example.com
git -C "$remote_seed" config user.name Buildr
printf '# API main\n' > "$remote_seed/README.md"
git -C "$remote_seed" add README.md
git -C "$remote_seed" commit -m main >/dev/null
git -C "$remote_seed" remote add origin "$remote_repo"
git -C "$remote_seed" push -u origin main >/dev/null
git -C "$remote_seed" checkout -b feature >/dev/null
printf '# API feature\n' > "$remote_seed/FEATURE.md"
git -C "$remote_seed" add FEATURE.md
git -C "$remote_seed" commit -m feature >/dev/null
git -C "$remote_seed" push -u origin feature >/dev/null
git -C "$remote_repo" symbolic-ref HEAD refs/heads/main
git -C "$project_repo" init >/dev/null
git -C "$project_repo" config user.email buildr@example.com
git -C "$project_repo" config user.name Buildr
printf '# Platform Project\n' > "$project_repo/README.md"
git -C "$project_repo" add README.md
git -C "$project_repo" commit -m init >/dev/null
git -C "$local_repo" init >/dev/null

cat > "$remote_skill_dir/SKILL.md" <<'EOF'
---
name: remote-review
description: Remote review skill
---

# Remote Review
EOF
remote_skill_hash="$(openssl dgst -sha256 -r "$remote_skill_dir/SKILL.md" | awk '{print $1}')"
remote_skill_port_file="$remote_skill_dir/port"
node - "$remote_skill_dir" "$remote_skill_port_file" <<'NODE' >/tmp/buildr-product-mvp-remote-skill-http.log 2>&1 &
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const root = process.argv[2];
const portFile = process.argv[3];
const server = http.createServer((req, res) => {
  const pathname = new URL(req.url, 'http://127.0.0.1').pathname;
  if (pathname !== '/SKILL.md') {
    res.writeHead(404);
    res.end('not found');
    return;
  }
  res.writeHead(200, { 'content-type': 'text/markdown; charset=utf-8' });
  res.end(fs.readFileSync(path.join(root, 'SKILL.md'), 'utf8'));
});
server.listen(0, '127.0.0.1', () => {
  fs.writeFileSync(portFile, String(server.address().port));
});
NODE
remote_skill_pid="$!"
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if [[ -s "$remote_skill_port_file" ]]; then
    break
  fi
  sleep 0.2
done
remote_skill_port="$(cat "$remote_skill_port_file")"

node --check "$buildr" >/dev/null
