function text(id, value) { const element = document.getElementById(id); if (element) element.textContent = value; }

export async function renderProjectEdit({ root, api, onWorkspace, onBreadcrumb, params }) {
  const code = params.projectCode;
  root.innerHTML = `<section class="detail-page-header"><a class="back-link" href="/projects/${encodeURIComponent(code)}" data-route>← 返回项目详情</a><p class="eyebrow">编辑项目</p><h1 id="project-edit-name">正在读取…</h1><p class="page-copy">仅修改稳定元数据；身份、来源和 Git 观察状态保持只读。</p></section><div id="project-edit-alert" class="alert hidden" role="status"></div><section class="edit-layout"><form id="project-edit-form" class="edit-form"><div class="section-heading"><div><h2>名称与说明</h2></div><span id="project-save-state" class="state">正在读取</span></div><label>名称<input id="project-name" autocomplete="off" required></label><label>说明<textarea id="project-description" rows="6" required></textarea></label><div class="actions"><a class="button secondary" href="/projects/${encodeURIComponent(code)}" data-route>取消</a><button id="project-save-button" class="button primary" type="submit">保存修改</button></div></form><aside class="read-only-section"><details class="technical-details" open><summary>技术信息</summary><dl class="read-facts technical-facts"><div><dt>项目代码</dt><dd id="project-code">—</dd></div><div><dt>版本标识</dt><dd id="project-revision">—</dd></div><div><dt>来源路径</dt><dd id="project-path">—</dd></div></dl></details></aside></section>`;
  let current;
  function render(data) {
    current = data; const project = data.project; onBreadcrumb(['项目', project.name, '编辑']); text('project-edit-name', project.name); text('project-code', project.code); text('project-revision', data.revision); text('project-path', project.source.path); document.getElementById('project-name').value = project.name; document.getElementById('project-description').value = project.description;
    const readOnly = data.migrationRequired; for (const id of ['project-name', 'project-description', 'project-save-button']) document.getElementById(id).disabled = readOnly; text('project-save-state', readOnly ? '迁移前只读' : '可以修改'); const alert = document.getElementById('project-edit-alert'); alert.classList.toggle('hidden', !readOnly); alert.textContent = readOnly ? data.nextActions.join(' ') : '';
  }
  try { const [workspace, data] = await Promise.all([api('/api/v1/workspace'), api(`/api/v1/projects/${encodeURIComponent(code)}`)]); onWorkspace(workspace); render(data); } catch (error) { root.innerHTML = `<section class="page-header"><h1>无法编辑项目</h1><p class="page-copy"></p></section>`; root.querySelector('.page-copy').textContent = error.message; return; }
  document.getElementById('project-edit-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = document.getElementById('project-save-button'); button.disabled = true; text('project-save-state', '正在保存…'); try { const updated = await api(`/api/v1/projects/${encodeURIComponent(code)}`, { method: 'PUT', body: JSON.stringify({ revision: current.revision, name: document.getElementById('project-name').value, description: document.getElementById('project-description').value }) }); render(updated); text('project-save-state', '保存成功'); } catch (error) { text('project-save-state', error.code === 'project_revision_conflict' ? 'registry 已变化，请刷新' : error.message); button.disabled = false; } });
}
