function text(id, value) { const element = document.getElementById(id); if (element) element.textContent = value; }

export async function renderServiceEdit({ root, api, onWorkspace, onBreadcrumb, params }) {
  const { projectCode, serviceCode } = params;
  const detail = `/services/${encodeURIComponent(projectCode)}/${encodeURIComponent(serviceCode)}`;
  root.innerHTML = `<section class="detail-page-header"><a class="back-link" href="${detail}" data-route>← 返回服务详情</a><p class="eyebrow">编辑服务</p><h1 id="service-edit-name">正在读取…</h1><p class="page-copy">只修改稳定 metadata；来源和 Git 观察状态保持只读。</p></section><div id="service-edit-alert" class="alert hidden" role="status"></div><section class="edit-layout"><form id="service-edit-form" class="edit-form"><div class="section-heading"><div><h2>名称、说明与类型</h2></div><span id="service-save-state" class="state">正在读取</span></div><label>名称<input id="service-name" autocomplete="off" required></label><label>说明<textarea id="service-description" rows="6" required></textarea></label><label>类型<input id="service-type" autocomplete="off" required></label><div class="actions"><a class="button secondary" href="${detail}" data-route>取消</a><button id="service-save-button" class="button primary" type="submit">保存修改</button></div></form><aside class="technical-sidebar"><details open><summary>只读身份</summary><dl class="fact-list"><div><dt>代码</dt><dd id="service-code">—</dd></div><div><dt>Revision</dt><dd id="service-revision">—</dd></div><div><dt>来源路径</dt><dd id="service-path">—</dd></div></dl></details></aside></section>`;
  let current;
  function render(data) {
    current = data; const service = data.service; onBreadcrumb(['项目', projectCode, '服务', service.name, '编辑']); text('service-edit-name', service.name); text('service-code', service.code); text('service-revision', data.revision); text('service-path', service.source.path); document.getElementById('service-name').value = service.name; document.getElementById('service-description').value = service.description; document.getElementById('service-type').value = service.type;
    const readOnly = data.migrationRequired; for (const id of ['service-name', 'service-description', 'service-type', 'service-save-button']) document.getElementById(id).disabled = readOnly; text('service-save-state', readOnly ? '迁移前只读' : '可以修改'); const alert = document.getElementById('service-edit-alert'); alert.classList.toggle('hidden', !readOnly); alert.textContent = readOnly ? data.nextActions.join(' ') : '';
  }
  try { const [workspace, data] = await Promise.all([api('/api/v1/workspace'), api(`/api/v1/projects/${encodeURIComponent(projectCode)}/services/${encodeURIComponent(serviceCode)}`)]); onWorkspace(workspace); render(data); } catch (error) { root.innerHTML = `<section class="page-header"><h1>无法编辑服务</h1><p class="page-copy"></p></section>`; root.querySelector('.page-copy').textContent = error.message; return; }
  document.getElementById('service-edit-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = document.getElementById('service-save-button'); button.disabled = true; text('service-save-state', '正在保存…'); try { const updated = await api(`/api/v1/projects/${encodeURIComponent(projectCode)}/services/${encodeURIComponent(serviceCode)}`, { method: 'PUT', body: JSON.stringify({ revision: current.revision, name: document.getElementById('service-name').value, description: document.getElementById('service-description').value, type: document.getElementById('service-type').value }) }); render(updated); text('service-save-state', '保存成功'); } catch (error) { text('service-save-state', error.code === 'service_revision_conflict' ? 'registry 已变化，请刷新' : error.message); button.disabled = false; } });
}
