import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {
  createRuntimeContext,
  getRuntimeAdapter,
  reconcileRuntimePlan,
} from './adapter-contract.mjs';
import {
  buildSkillRenderPlan,
  hasManagedSkillMarker,
  resolvePackageAgentSkill,
  resolveRenderSkills,
} from './render-claude-code.mjs';
import {
  buildRuleDiscoveryPlan,
  hasManagedRulesMarker,
  planRulesRender,
  resolveRuleScope,
} from './render-claude-code-rules.mjs';

const INSTALL_PLAN_MARKER = '<!-- Generated by Buildr. Agent action required.';

export function runtimeSkillScope(scope) {
  const parts = scope.split('/');
  return parts[0] === 'projects' && parts[1] ? `projects/${parts[1]}` : '.';
}

function skillDiagnostic(item, product) {
  const installPlan = item.targetFile.includes(`${path.sep}skill-install-plans${path.sep}`);
  if (installPlan) {
    return {
      label: `workspace Skill install plan ${path.basename(item.targetFile, '.md')}`,
      code: 'runtime.skill_agent_action_required',
      repair: 'agent-install',
      repairs: { missing: 'skills-render', stale: 'agent-install' },
      currentStatus: 'warning',
    };
  }
  const conflict = `Refusing to overwrite non-Buildr-managed file: ${item.targetFile}`;
  return product
    ? { label: 'product Agent Skill buildr', codes: { ok: 'runtime.product_skill_ok', missing: 'runtime.product_skill_missing', stale: 'runtime.product_skill_stale', conflict: 'runtime.product_skill_conflict' }, messages: { conflict }, repair: 'skill-install' }
    : { label: `workspace Skill ${path.basename(path.dirname(item.targetFile))}`, codes: { ok: 'runtime.skill_ok', missing: 'runtime.skill_missing', stale: 'runtime.skill_stale', conflict: 'runtime.skill_conflict' }, messages: { conflict }, repair: 'skills-render' };
}

function decorateSkillWrites(items, product = false) {
  return items.map((item) => ({
    ...item,
    capability: product ? 'product-buildr-skill' : item.targetFile.includes(`${path.sep}skill-install-plans${path.sep}`) ? 'skill-install-plans' : 'workspace-project-skills',
    isManaged: (content) => hasManagedSkillMarker(content) || content.includes(INSTALL_PLAN_MARKER),
    diagnostic: skillDiagnostic(item, product),
  }));
}

function ruleFinding(status, scope, message, metadata = {}) {
  return { status, path: scope, message, userActionRequired: status !== 'info' && status !== 'ok', ...metadata };
}

function liveReferenceBridge(current, targetFile, sourceFile) {
  if (!hasManagedRulesMarker(current) || !current.includes('@AGENTS.md')) return false;
  return path.resolve(path.dirname(targetFile), 'AGENTS.md') === path.resolve(sourceFile);
}

function referenceMetadataStale(current, sourceFile) {
  const hash = current.match(/\bhash:\s*([a-f0-9]{64})\b/i)?.[1]?.toLowerCase();
  if (!hash) return false;
  return hash !== crypto.createHash('sha256').update(fs.readFileSync(sourceFile)).digest('hex');
}

function assembleRules(repoRoot, targetRoot, scopeInfo, adapter) {
  const discovery = buildRuleDiscoveryPlan(repoRoot, scopeInfo);
  const findings = [
    ...discovery.warnings.map((message) => ruleFinding('warning', scopeInfo.scope, message, { code: 'runtime.scope_legacy', canonicalScope: scopeInfo.scope })),
    ...discovery.boundaries.map((boundary) => ruleFinding('info', boundary.path, `Rules discovery skipped boundary: ${boundary.reason}.`, { code: 'runtime.rules_discovery_boundary', boundaryReason: boundary.reason, userActionRequired: false })),
  ];
  if (discovery.files.length === 0) {
    findings.push(ruleFinding(adapter.projection === 'native-agents' ? 'missing' : 'conflict', adapter.projection === 'native-agents' ? 'AGENTS.md' : 'CLAUDE.md', `No AGENTS.md files found for scope: ${scopeInfo.scope}.`, { code: adapter.projection === 'native-agents' ? 'runtime.codex_rules_missing' : 'runtime.rules_bridge_missing' }));
    return { writes: [], removals: [], nativeAssets: [], actions: [], findings, discovery };
  }
  if (adapter.projection === 'native-agents') {
    return {
      writes: [], removals: [], actions: [], findings, discovery,
      nativeAssets: discovery.files.map((targetFile) => ({ targetFile, source: path.relative(repoRoot, targetFile), diagnostic: { label: 'Codex native AGENTS.md rule asset', code: 'runtime.codex_rules_ok' } })),
    };
  }
  const planned = planRulesRender(repoRoot, targetRoot, scopeInfo);
  for (const conflict of planned.conflicts) findings.push(ruleFinding('conflict', scopeInfo.scope, conflict, { code: 'runtime.rules_bridge_conflict' }));
  const diagnostic = { label: 'Claude Code rules bridge', codes: { ok: 'runtime.reference_bridge_ok', missing: 'runtime.rules_bridge_missing', stale: 'runtime.rules_bridge_stale', conflict: 'runtime.rules_bridge_conflict', orphan: 'runtime.rules_bridge_orphan' }, repair: 'rules-render' };
  for (const item of planned.actions) {
    if (!item.sourceFile || !fs.existsSync(item.targetFile)) continue;
    const current = fs.readFileSync(item.targetFile, 'utf8');
    if (liveReferenceBridge(current, item.targetFile, item.sourceFile) && referenceMetadataStale(current, item.sourceFile)) {
      findings.push(ruleFinding('info', path.relative(targetRoot, item.targetFile).split(path.sep).join('/'), `${path.relative(repoRoot, item.sourceFile).split(path.sep).join('/')} bridge metadata hash is stale, but AGENTS.md is referenced live.`, { code: 'runtime.reference_bridge_metadata_stale', bridgeType: 'reference', impact: 'none', userActionRequired: false, repair: 'optional-rules-render', suggestion: 'No action required. Source is referenced live. Run rules render only if you want to refresh metadata.' }));
    }
  }
  return {
    writes: planned.actions.filter((item) => item.content !== null).map((item) => ({ ...item, capability: 'rules-entry', isManaged: hasManagedRulesMarker, matchesCurrent: (current) => liveReferenceBridge(current, item.targetFile, item.sourceFile), diagnostic })),
    removals: planned.actions.filter((item) => item.content === null).map((item) => ({ targetFile: item.targetFile, capability: 'rules-entry', isManaged: hasManagedRulesMarker, diagnostic })),
    nativeAssets: [], actions: planned.actions, findings, discovery: planned.discovery,
  };
}

export function assembleRuntimeProjection(options) {
  const repoRoot = path.resolve(options.repoRoot);
  const targetRoot = path.resolve(options.targetRoot ?? repoRoot);
  if (!fs.existsSync(targetRoot) || !fs.statSync(targetRoot).isDirectory()) throw new Error(`Target directory does not exist: ${targetRoot}`);
  const adapter = getRuntimeAdapter(options.adapterId);
  const selection = { productSkill: false, rules: false, workspaceSkills: false, ...(options.selection || {}) };
  const scopeInfo = resolveRuleScope(repoRoot, options.scope ?? '.');
  const skillScope = runtimeSkillScope(scopeInfo.scope);
  const skillConflicts = [];
  const productWrites = selection.productSkill
    ? decorateSkillWrites(buildSkillRenderPlan(repoRoot, targetRoot, [resolvePackageAgentSkill(adapter.id, 'buildr')], adapter.id, { deferConflicts: true, conflicts: skillConflicts }), true)
    : [];
  const workspaceSkills = selection.workspaceSkills ? resolveRenderSkills(repoRoot, skillScope, adapter.id) : [];
  const workspaceWrites = decorateSkillWrites(buildSkillRenderPlan(repoRoot, targetRoot, workspaceSkills, adapter.id, { deferConflicts: true, conflicts: skillConflicts }));
  const rules = selection.rules ? assembleRules(repoRoot, targetRoot, scopeInfo, adapter) : { writes: [], removals: [], nativeAssets: [], actions: [], findings: [], discovery: { boundaries: [], warnings: [] } };
  const warnings = workspaceSkills.filter((skill) => skill.resolved && !skill.resolved.integrity)
    .map((skill) => `workspace Skill ${skill.id} uses a remote resolved source without integrity.`);
  const context = createRuntimeContext({
    adapterId: adapter.id, targetRoot, scope: scopeInfo.scope,
    rules, skills: { writes: [...productWrites, ...workspaceWrites], removals: options.removals || [] },
    findings: [...rules.findings, ...skillConflicts.map((message) => ({ status: 'conflict', path: skillScope, message, code: 'runtime.skill_conflict', userActionRequired: true }))], warnings,
  });
  return { plan: adapter.planRuntime(context), scopeInfo, discovery: rules.discovery, selection };
}

function summarize(findings) {
  const counts = { ok: 0, info: 0, warning: 0, missing: 0, stale: 0, orphan: 0, conflict: 0 };
  for (const finding of findings) counts[finding.status] = (counts[finding.status] ?? 0) + 1;
  return counts;
}

export function repairCommands(result, adapterId) {
  const target = path.relative(process.cwd(), result.targetRoot).split(path.sep).join('/') || '.';
  const has = (repair) => result.findings.some((item) => ['missing', 'stale', 'orphan'].includes(item.status) && item.repair === repair);
  const commands = [];
  if (has('skill-install')) commands.push(`buildr skill install ${adapterId} --target ${target}`);
  if (has('rules-render')) commands.push(`buildr rules render ${adapterId} --scope ${result.scope} --target ${target}`);
  if (has('skills-render')) commands.push(`buildr skills render ${adapterId} --scope ${runtimeSkillScope(result.scope)} --target ${target}`);
  return commands;
}

export function checkRuntimeProjection(options) {
  const assembled = assembleRuntimeProjection({ ...options, selection: { productSkill: true, rules: true, workspaceSkills: true } });
  const reconciled = reconcileRuntimePlan(assembled.plan, { compareOnly: true });
  const counts = summarize(reconciled.findings);
  const result = { ...reconciled, counts, exitCode: counts.conflict ? 2 : counts.missing || counts.stale || counts.orphan ? 1 : 0, requestedScope: assembled.scopeInfo.requestedScope, discoveryBoundaries: assembled.discovery.boundaries };
  result.repairCommands = repairCommands(result, options.adapterId);
  return result;
}

export function printRuntimeProjectionReport(result, label) {
  console.log(`${label} runtime check for ${result.scope}`);
  console.log(`Target: ${result.targetRoot}`);
  console.log(`Status: ${Object.entries(result.counts).map(([key, value]) => `${key}=${value}`).join(' ')}`);
  console.log('');
  for (const finding of result.findings) console.log(`[${finding.status}] ${finding.path} - ${finding.message}`);
  if (result.repairCommands.length) {
    console.log('\nSuggested commands:');
    for (const command of result.repairCommands) console.log(`  ${command}`);
  }
}
