import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {
  createRuntimeContext,
  createRuntimePlan,
  getRuntimeAdapter,
  assertRuntimeTargetPath,
  reconcileRuntimePlan,
  selectAdapterImplementation,
} from './adapter-contract.mjs';
import {
  buildSkillRenderPlan,
  hasManagedSkillMarker,
  resolvePackageAgentSkill,
  resolveRenderSkills,
} from './render-claude-code.mjs';
import { resolveCapabilityRoutingEvidence } from './skills/capabilities.mjs';
import {
  buildRuleDiscoveryPlan,
  hasManagedRulesMarker,
  planRulesRender,
  resolveRuleScope,
} from './render-claude-code-rules.mjs';

const INSTALL_PLAN_MARKER = '<!-- Generated by Buildr. Agent action required.';
const ADAPTER_RULE_MARKER = '<!-- Generated by Buildr. Agent adapter:';
const VENDOR_DISCOVERY_EXCLUDED = new Set(['.git', '.hg', '.svn', '.worktrees', '.agents', '.claude', '.cursor', '.qoder', '.trae', '.codebuddy', '.workbuddy', 'node_modules', 'vendor', 'dist', 'build', 'coverage']);

export function runtimeSkillScope(scope) {
  const parts = scope.split('/');
  return parts[0] === 'projects' && parts[1] ? `projects/${parts[1]}` : '.';
}

function skillDiagnostic(item, product) {
  const installPlan = item.targetFile.includes(`${path.sep}skill-install-plans${path.sep}`);
  if (installPlan) {
    return {
      label: `workspace Skill install plan ${path.basename(item.targetFile, '.md')}`,
      code: 'runtime.skill_agent_action_required',
      repair: 'agent-install',
      repairs: { missing: 'skills-render', stale: 'agent-install' },
      currentStatus: 'warning',
    };
  }
  const conflict = `Refusing to overwrite non-Buildr-managed file: ${item.targetFile}`;
  return product
    ? { label: 'product Agent Skill buildr', codes: { ok: 'runtime.product_skill_ok', missing: 'runtime.product_skill_missing', stale: 'runtime.product_skill_stale', conflict: 'runtime.product_skill_conflict' }, messages: { conflict }, repair: 'skill-install' }
    : { label: `workspace Skill ${path.basename(path.dirname(item.targetFile))}`, codes: { ok: 'runtime.skill_ok', missing: 'runtime.skill_missing', stale: 'runtime.skill_stale', conflict: 'runtime.skill_conflict' }, messages: { conflict }, repair: 'skills-render' };
}

function decorateSkillWrites(items, product = false) {
  return items.map((item) => ({
    ...item,
    capability: product ? 'product-buildr-skill' : item.targetFile.includes(`${path.sep}skill-install-plans${path.sep}`) ? 'skill-install-plans' : 'workspace-project-skills',
    isManaged: (content) => hasManagedSkillMarker(content) || content.includes(INSTALL_PLAN_MARKER),
    diagnostic: skillDiagnostic(item, product),
  }));
}

function ruleFinding(status, scope, message, metadata = {}) {
  return { status, path: scope, message, userActionRequired: status !== 'info' && status !== 'ok', ...metadata };
}

function liveReferenceBridge(current, targetFile, sourceFile) {
  if (!hasManagedRulesMarker(current) || !current.includes('@AGENTS.md')) return false;
  return path.resolve(path.dirname(targetFile), 'AGENTS.md') === path.resolve(sourceFile);
}

function referenceMetadataStale(current, sourceFile) {
  const hash = current.match(/\bhash:\s*([a-f0-9]{64})\b/i)?.[1]?.toLowerCase();
  if (!hash) return false;
  return hash !== crypto.createHash('sha256').update(fs.readFileSync(sourceFile)).digest('hex');
}

function toPosixRelative(root, file) {
  return path.relative(root, file).split(path.sep).join('/') || '.';
}

function adapterRuleManaged(content) {
  return typeof content === 'string' && content.includes(ADAPTER_RULE_MARKER);
}

function managedRuleSource(repoRoot, targetFile) {
  const content = fs.readFileSync(targetFile, 'utf8');
  const relative = content.match(/<!-- Generated by Buildr\. Agent adapter:[^\n]*; source: ([^;]+); scope:/)?.[1];
  if (!relative) return null;
  const sourceFile = path.resolve(repoRoot, relative);
  return sourceFile === repoRoot || sourceFile.startsWith(`${repoRoot}${path.sep}`) ? sourceFile : null;
}

function sourceParticipatesInScope(repoRoot, scopeInfo, targetFile) {
  if (scopeInfo.scope === '.') return true;
  const sourceFile = managedRuleSource(repoRoot, targetFile);
  if (!sourceFile) return false;
  const sourceDirectory = path.dirname(sourceFile);
  return sourceDirectory === scopeInfo.scopeRoot
    || sourceDirectory.startsWith(`${scopeInfo.scopeRoot}${path.sep}`)
    || scopeInfo.scopeRoot.startsWith(`${sourceDirectory}${path.sep}`);
}

function actionFor(targetRoot, targetFile, content) {
  assertRuntimeTargetPath(targetRoot, targetFile, 'runtime rules target');
  if (!fs.existsSync(targetFile)) return 'created';
  return fs.readFileSync(targetFile, 'utf8') === content ? 'unchanged' : 'updated';
}

function sourceScope(repoRoot, sourceFile) {
  return toPosixRelative(repoRoot, path.dirname(sourceFile));
}

function sourceId(repoRoot, sourceFile) {
  const relative = toPosixRelative(repoRoot, sourceFile);
  const directory = path.posix.dirname(relative);
  const depth = directory === '.' ? 0 : directory.split('/').length;
  const slug = (directory === '.' ? 'root' : directory).replace(/[^A-Za-z0-9._-]+/g, '-').slice(0, 72);
  const hash = crypto.createHash('sha256').update(relative).digest('hex').slice(0, 10);
  return `${String(depth).padStart(3, '0')}-${slug}-${hash}`;
}

function vendorRuleTarget(repoRoot, targetRoot, sourceFile, rules) {
  if (rules.format === 'cursor-mdc') {
    const relativeDirectory = path.relative(repoRoot, path.dirname(sourceFile));
    return path.join(targetRoot, relativeDirectory, '.cursor', 'rules', 'buildr.mdc');
  }
  if (rules.format === 'qoder-markdown') {
    return path.join(targetRoot, '.qoder', 'rules', 'buildr', `${sourceId(repoRoot, sourceFile)}.md`);
  }
  const relativeDirectory = path.relative(repoRoot, path.dirname(sourceFile));
  return path.join(targetRoot, relativeDirectory, '.trae', 'rules', 'buildr.md');
}

function vendorRuleContent(repoRoot, sourceFile, rules, adapterId) {
  const relative = toPosixRelative(repoRoot, sourceFile);
  const scope = sourceScope(repoRoot, sourceFile);
  const body = fs.readFileSync(sourceFile, 'utf8').trimEnd();
  const marker = `${ADAPTER_RULE_MARKER} ${adapterId}; source: ${relative}; scope: ${scope}. Do not edit. -->`;
  if (rules.format === 'cursor-mdc') {
    const frontmatter = ['---', `description: ${JSON.stringify(scope === '.' ? 'Buildr workspace root rules' : `Buildr rules for ${scope}`)}`, 'globs:', 'alwaysApply: true', '---'];
    return [...frontmatter, marker, '', body, ''].join('\n');
  }
  if (rules.format === 'qoder-markdown') {
    const root = scope === '.';
    const frontmatter = root
      ? ['---', 'trigger: always_on', '---']
      : ['---', 'trigger: glob', `glob: ${JSON.stringify(`${scope}/**`)}`, '---'];
    return [...frontmatter, marker, '', body, ''].join('\n');
  }
  return ['---', 'alwaysApply: true', '---', marker, '', `Source: \`${relative}\``, `Scope: \`${scope}\``, '', body, ''].join('\n');
}

function discoverQoderManagedTargets(targetRoot) {
  const directory = path.join(targetRoot, '.qoder', 'rules', 'buildr');
  if (!fs.existsSync(directory) || fs.lstatSync(directory).isSymbolicLink() || !fs.lstatSync(directory).isDirectory()) return [];
  return fs.readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) => path.join(directory, entry.name))
    .filter((file) => adapterRuleManaged(fs.readFileSync(file, 'utf8')));
}

function blockedRuntimeDirectories(targetRoot, discovery) {
  return new Set((discovery.boundaries || []).map((boundary) => path.resolve(targetRoot, boundary.path)));
}

function discoverCursorManagedTargets(targetRoot, discovery) {
  const files = [];
  const blocked = blockedRuntimeDirectories(targetRoot, discovery);
  function walk(directory) {
    const candidate = path.join(directory, '.cursor', 'rules', 'buildr.mdc');
    if (fs.existsSync(candidate) && !fs.lstatSync(candidate).isSymbolicLink() && fs.lstatSync(candidate).isFile() && adapterRuleManaged(fs.readFileSync(candidate, 'utf8'))) files.push(candidate);
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const child = path.join(directory, entry.name);
      if (!entry.isDirectory() || entry.isSymbolicLink() || VENDOR_DISCOVERY_EXCLUDED.has(entry.name) || blocked.has(path.resolve(child))) continue;
      walk(child);
    }
  }
  walk(targetRoot);
  return files;
}

function discoverTraeManagedTargets(targetRoot, discovery) {
  const files = [];
  const blocked = blockedRuntimeDirectories(targetRoot, discovery);
  function walk(directory) {
    const candidate = path.join(directory, '.trae', 'rules', 'buildr.md');
    if (fs.existsSync(candidate) && !fs.lstatSync(candidate).isSymbolicLink() && fs.lstatSync(candidate).isFile() && adapterRuleManaged(fs.readFileSync(candidate, 'utf8'))) files.push(candidate);
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const child = path.join(directory, entry.name);
      if (!entry.isDirectory() || entry.isSymbolicLink() || VENDOR_DISCOVERY_EXCLUDED.has(entry.name) || blocked.has(path.resolve(child))) continue;
      walk(child);
    }
  }
  walk(targetRoot);
  return files;
}

function rootIndexBridgeContent(repoRoot, discovery, adapter) {
  const sources = discovery.files.map((source) => toPosixRelative(repoRoot, source));
  const lines = [
    `${ADAPTER_RULE_MARKER} ${adapter.id}; type: root-index-reference. Do not edit. -->`,
    '# Buildr Rules Bridge',
    '',
    '执行任何 workspace 任务前，必须先读取并遵循根 `AGENTS.md`。',
    '每当读取、分析或修改某个文件或目录时，必须再读取从 workspace root 到该路径之间所有存在的 `AGENTS.md`，按由宽到窄的顺序应用；不得读取不相关兄弟目录的规则。',
    '下列索引仅用于发现规则文件，普通 Markdown 链接不代表内容已经自动加载：',
    '',
    ...sources.map((source) => `- [${source}](${source})`),
    '',
  ];
  const content = lines.join('\n');
  if (adapter.traits.rules.maxChars && content.length > adapter.traits.rules.maxChars) {
    throw new Error(`${adapter.displayName} rules bridge exceeds ${adapter.traits.rules.maxChars} characters.`);
  }
  return content;
}

function rootIndexTarget(targetRoot, rules) {
  const relative = rules.targetPattern.replace(/^<workspace-root>\//, '');
  return path.join(targetRoot, relative);
}

function assembleNativeRecursiveRules({ repoRoot, discovery, findings, adapter }) {
  const diagnostics = adapter.traits.rules.diagnostics;
  return {
    writes: [], removals: [], actions: [], findings, discovery,
    nativeAssets: discovery.files.map((targetFile) => ({ targetFile, source: path.relative(repoRoot, targetFile), diagnostic: { label: diagnostics.label, code: diagnostics.okCode } })),
  };
}

function assembleReferenceBridgeRules({ repoRoot, targetRoot, scopeInfo, discovery, findings, adapter }) {
  if (adapter.traits.rules.placement === 'root-index') {
    if (discovery.files.length === 0) {
      const targetFile = rootIndexTarget(targetRoot, adapter.traits.rules);
      const managed = fs.existsSync(targetFile) && fs.statSync(targetFile).isFile() && adapterRuleManaged(fs.readFileSync(targetFile, 'utf8'));
      const diagnostic = { label: adapter.traits.rules.diagnostics.label, codes: adapter.traits.rules.diagnostics.codes, repair: 'rules-render' };
      const removals = managed ? [{ targetFile, capability: 'rules-entry', isManaged: adapterRuleManaged, diagnostic }] : [];
      return { writes: [], removals, nativeAssets: [], actions: removals.map(() => ({ action: 'removed', sourceFile: null, targetFile, content: null })), findings, discovery };
    }
    const content = rootIndexBridgeContent(repoRoot, discovery, adapter);
    const targetFile = rootIndexTarget(targetRoot, adapter.traits.rules);
    const diagnostic = { label: adapter.traits.rules.diagnostics.label, codes: adapter.traits.rules.diagnostics.codes, repair: 'rules-render' };
    const item = { action: actionFor(targetRoot, targetFile, content), sourceFile: discovery.files[0], sourceFiles: discovery.files, targetFile, content };
    return {
      writes: [{ ...item, capability: 'rules-entry', isManaged: adapterRuleManaged, diagnostic }],
      removals: [], nativeAssets: [], actions: [item], findings, discovery,
    };
  }
  const planned = planRulesRender(repoRoot, targetRoot, scopeInfo);
  for (const conflict of planned.conflicts) findings.push(ruleFinding('conflict', scopeInfo.scope, conflict, { code: 'runtime.rules_bridge_conflict' }));
  const diagnostic = { label: adapter.traits.rules.diagnostics.label, codes: adapter.traits.rules.diagnostics.codes, repair: 'rules-render' };
  for (const item of planned.actions) {
    if (!item.sourceFile || !fs.existsSync(item.targetFile)) continue;
    const current = fs.readFileSync(item.targetFile, 'utf8');
    if (liveReferenceBridge(current, item.targetFile, item.sourceFile) && referenceMetadataStale(current, item.sourceFile)) {
      findings.push(ruleFinding('info', path.relative(targetRoot, item.targetFile).split(path.sep).join('/'), `${path.relative(repoRoot, item.sourceFile).split(path.sep).join('/')} bridge metadata hash is stale, but AGENTS.md is referenced live.`, { code: 'runtime.reference_bridge_metadata_stale', bridgeType: 'reference', impact: 'none', userActionRequired: false, repair: 'optional-rules-render', suggestion: 'No action required. Source is referenced live. Run rules render only if you want to refresh metadata.' }));
    }
  }
  return {
    writes: planned.actions.filter((item) => item.content !== null).map((item) => ({ ...item, capability: 'rules-entry', isManaged: hasManagedRulesMarker, matchesCurrent: (current) => liveReferenceBridge(current, item.targetFile, item.sourceFile), diagnostic })),
    removals: planned.actions.filter((item) => item.content === null).map((item) => ({ targetFile: item.targetFile, capability: 'rules-entry', isManaged: hasManagedRulesMarker, diagnostic })),
    nativeAssets: [], actions: planned.actions, findings, discovery: planned.discovery,
  };
}

function assembleVendorRuleFiles({ repoRoot, targetRoot, scopeInfo, discovery, findings, adapter }) {
  const rules = adapter.traits.rules;
  const diagnostic = { label: rules.diagnostics.label, codes: rules.diagnostics.codes, repair: 'rules-render' };
  const actions = discovery.files.map((sourceFile) => {
    const targetFile = vendorRuleTarget(repoRoot, targetRoot, sourceFile, rules);
    const content = vendorRuleContent(repoRoot, sourceFile, rules, adapter.id);
    if (rules.maxChars && content.length > rules.maxChars) throw new Error(`${adapter.displayName} rule file exceeds ${rules.maxChars} characters: ${toPosixRelative(targetRoot, targetFile)}`);
    return { action: actionFor(targetRoot, targetFile, content), sourceFile, targetFile, content };
  });
  if (rules.maxChars && actions.reduce((sum, item) => sum + item.content.length, 0) > rules.maxChars) {
    throw new Error(`${adapter.displayName} active rule files exceed ${rules.maxChars} total characters.`);
  }
  const expected = new Set(actions.map((item) => path.resolve(item.targetFile)));
  const existing = rules.format === 'cursor-mdc'
    ? discoverCursorManagedTargets(targetRoot, discovery)
    : rules.format === 'qoder-markdown'
      ? discoverQoderManagedTargets(targetRoot)
      : discoverTraeManagedTargets(targetRoot, discovery);
  const removals = existing
    .filter((targetFile) => sourceParticipatesInScope(repoRoot, scopeInfo, targetFile))
    .filter((targetFile) => !expected.has(path.resolve(targetFile)))
    .map((targetFile) => ({ targetFile, capability: 'rules-entry', isManaged: adapterRuleManaged, diagnostic }));
  return {
    writes: actions.map((item) => ({ ...item, capability: 'rules-entry', isManaged: adapterRuleManaged, diagnostic })),
    removals,
    nativeAssets: [], actions: [...actions, ...removals.map((item) => ({ action: 'removed', sourceFile: null, targetFile: item.targetFile, content: null }))], findings, discovery,
  };
}

const RULE_IMPLEMENTATIONS = Object.freeze({
  'native-recursive': assembleNativeRecursiveRules,
  'reference-bridge': assembleReferenceBridgeRules,
  'vendor-rule-files': assembleVendorRuleFiles,
});

function assembleRules(repoRoot, targetRoot, scopeInfo, adapter) {
  const discoveryScope = adapter.traits.rules.placement === 'root-index'
    ? resolveRuleScope(repoRoot, '.')
    : scopeInfo;
  const discovery = buildRuleDiscoveryPlan(repoRoot, discoveryScope);
  const findings = [
    ...discovery.warnings.map((message) => ruleFinding('warning', scopeInfo.scope, message, { code: 'runtime.scope_legacy', canonicalScope: scopeInfo.scope })),
    ...discovery.boundaries.map((boundary) => ruleFinding('info', boundary.path, `Rules discovery skipped boundary: ${boundary.reason}.`, { code: 'runtime.rules_discovery_boundary', boundaryReason: boundary.reason, userActionRequired: false })),
  ];
  const diagnostics = adapter.traits.rules.diagnostics;
  if (discovery.files.length === 0) {
    findings.push(ruleFinding(diagnostics.missingStatus, diagnostics.missingPath, `No AGENTS.md files found for scope: ${scopeInfo.scope}.`, { code: diagnostics.missingCode }));
  }
  const implementation = selectAdapterImplementation(adapter, 'rules', RULE_IMPLEMENTATIONS);
  return implementation({ repoRoot, targetRoot, scopeInfo, discovery, findings, adapter });
}

export function assembleRuntimeProjection(options) {
  const repoRoot = path.resolve(options.repoRoot);
  const targetRoot = path.resolve(options.targetRoot ?? repoRoot);
  if (!fs.existsSync(targetRoot) || !fs.statSync(targetRoot).isDirectory()) throw new Error(`Target directory does not exist: ${targetRoot}`);
  const adapter = getRuntimeAdapter(options.adapterId);
  const selection = { productSkill: false, rules: false, workspaceSkills: false, ...(options.selection || {}) };
  const scopeInfo = resolveRuleScope(repoRoot, options.scope ?? '.');
  const skillScope = runtimeSkillScope(scopeInfo.scope);
  const skillConflicts = [];
  const workspaceSkills = selection.workspaceSkills ? resolveRenderSkills(repoRoot, skillScope, adapter.id) : [];
  const productSkill = selection.productSkill ? resolvePackageAgentSkill(adapter.id, 'buildr') : null;
  if (productSkill && selection.workspaceSkills) productSkill.capabilityRoutingEvidence = resolveCapabilityRoutingEvidence(repoRoot, adapter.id);
  const productWrites = productSkill
    ? decorateSkillWrites(buildSkillRenderPlan(repoRoot, targetRoot, [productSkill], adapter.id, { deferConflicts: true, conflicts: skillConflicts }), true)
    : [];
  const workspaceWrites = decorateSkillWrites(buildSkillRenderPlan(repoRoot, targetRoot, workspaceSkills, adapter.id, { deferConflicts: true, conflicts: skillConflicts }));
  const rules = selection.rules ? assembleRules(repoRoot, targetRoot, scopeInfo, adapter) : { writes: [], removals: [], nativeAssets: [], actions: [], findings: [], discovery: { boundaries: [], warnings: [] } };
  const warnings = workspaceSkills.filter((skill) => skill.resolved && !skill.resolved.integrity)
    .map((skill) => `workspace Skill ${skill.id} uses a remote resolved source without integrity.`);
  const context = createRuntimeContext({
    adapterId: adapter.id, targetRoot, scope: scopeInfo.scope,
    rules, skills: { writes: [...productWrites, ...workspaceWrites], removals: options.removals || [] },
    findings: [...rules.findings, ...skillConflicts.map((message) => ({ status: 'conflict', path: skillScope, message, code: 'runtime.skill_conflict', userActionRequired: true }))], warnings,
  });
  return { plan: adapter.planRuntime(context), scopeInfo, discovery: rules.discovery, selection };
}

function summarize(findings) {
  const counts = { ok: 0, info: 0, warning: 0, missing: 0, stale: 0, orphan: 0, conflict: 0 };
  for (const finding of findings) counts[finding.status] = (counts[finding.status] ?? 0) + 1;
  return counts;
}

export function repairCommands(result, adapterId) {
  const target = path.relative(process.cwd(), result.targetRoot).split(path.sep).join('/') || '.';
  const has = (repair) => result.findings.some((item) => ['missing', 'stale', 'orphan'].includes(item.status) && item.repair === repair);
  const commands = [];
  if (has('skill-install')) commands.push(`buildr skill install ${adapterId} --target ${target}`);
  if (has('rules-render')) commands.push(`buildr rules render ${adapterId} --scope ${result.scope} --target ${target}`);
  if (has('skills-render')) commands.push(`buildr skills render ${adapterId} --scope ${runtimeSkillScope(result.scope)} --target ${target}`);
  return commands;
}

export function checkRuntimeProjection(options) {
  const assembled = assembleRuntimeProjection({ ...options, selection: { productSkill: true, rules: true, workspaceSkills: true } });
  const fallback = assembleRuntimeProjection({ ...options, selection: { productSkill: true } });
  const fallbackProductWrites = new Map(fallback.plan.writes
    .filter((item) => item.capability === 'product-buildr-skill')
    .map((item) => [item.targetFile, item.content]));
  const writes = assembled.plan.writes.map((item) => {
    if (item.capability !== 'product-buildr-skill') return item;
    const fallbackContent = fallbackProductWrites.get(item.targetFile);
    return fallbackContent && fs.existsSync(item.targetFile) && fs.readFileSync(item.targetFile, 'utf8') === fallbackContent
      ? { ...item, content: fallbackContent }
      : item;
  });
  const reconciled = reconcileRuntimePlan(createRuntimePlan({ ...assembled.plan, writes }), { compareOnly: true });
  const counts = summarize(reconciled.findings);
  const result = { ...reconciled, counts, exitCode: counts.conflict ? 2 : counts.missing || counts.stale || counts.orphan ? 1 : 0, requestedScope: assembled.scopeInfo.requestedScope, discoveryBoundaries: assembled.discovery.boundaries };
  result.repairCommands = repairCommands(result, options.adapterId);
  return result;
}

export function printRuntimeProjectionReport(result, label) {
  console.log(`${label} runtime check for ${result.scope}`);
  console.log(`Target: ${result.targetRoot}`);
  console.log(`Status: ${Object.entries(result.counts).map(([key, value]) => `${key}=${value}`).join(' ')}`);
  console.log('');
  for (const finding of result.findings) console.log(`[${finding.status}] ${finding.path} - ${finding.message}`);
  if (result.repairCommands.length) {
    console.log('\nSuggested commands:');
    for (const command of result.repairCommands) console.log(`  ${command}`);
  }
}
