import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  parseInstallClaudeCodeBuildrSkillArgs,
  parseRenderClaudeCodeArgs,
} from '../../tools/runtime/skills/arguments.mjs';
import { parseSkillsManifest } from '../../tools/runtime/skills/manifests.mjs';
import {
  normalizeRelativePath,
  resolveSkillScope,
} from '../../tools/runtime/skills/primitives.mjs';
import {
  buildAgentInstallPlanContent,
  buildRuntimeSkillTarget,
  hasManagedSkillMarker,
} from '../../tools/runtime/skills/render-plan.mjs';

test('render 参数解析拒绝未知和缺失参数', (t) => {
  t.mock.method(console, 'error', () => {});
  assert.deepEqual(parseRenderClaudeCodeArgs(['--scope', '.', '--target', 'tmp']), { scope: '.', target: 'tmp' });
  assert.deepEqual(parseInstallClaudeCodeBuildrSkillArgs(['--target', 'tmp']), { target: 'tmp' });
  assert.throws(() => parseRenderClaudeCodeArgs(['--scope', '.'], 'buildr render'), /Missing required arguments/);
  assert.throws(() => parseRenderClaudeCodeArgs(['--scope', '.', '--target', 'tmp', '--extra'], 'buildr render'), /Unknown argument/);
});

test('scope 和相对路径解析保持在 workspace 内', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-runtime-scope-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(root, 'projects', 'demo'), { recursive: true });

  assert.equal(normalizeRelativePath('./projects/demo'), path.join('projects', 'demo'));
  assert.throws(() => normalizeRelativePath('../outside'), /stay inside repository/);
  assert.deepEqual(resolveSkillScope(root, '.'), { scope: '.', organizationRoot: root, projectRoot: null });
  assert.equal(resolveSkillScope(root, 'projects/demo').projectRoot, path.join(root, 'projects', 'demo'));
  assert.throws(() => resolveSkillScope(root, 'services/api'), /Unsupported scope/);
});

test('Skills manifest parser 保留本地、远端和 runtime 字段', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-skills-manifest-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const manifest = path.join(root, 'manifest.yml');
  fs.writeFileSync(manifest, [
    'schemaVersion: buildr.skills/v1',
    'skills:',
    '  - id: local-review',
    '    path: local-review',
    '    enabled: true',
    '    runtimes: ["codex", "claude-code"]',
    '  - id: remote-review',
    '    source:',
    '      kind: url',
    '      url: https://example.com/review',
    '    resolved:',
    '      kind: skill-url',
    '      url: https://example.com/SKILL.md',
    '      integrity: sha256-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    '',
  ].join('\n'));

  const skills = parseSkillsManifest(manifest);
  assert.equal(skills.length, 2);
  assert.deepEqual(skills[0].runtimes, ['codex', 'claude-code']);
  assert.equal(skills[0].enabled, true);
  assert.equal(skills[1].source.kind, 'url');
  assert.equal(skills[1].resolved.kind, 'skill-url');
});

test('runtime target、managed marker 和 Agent install plan 可独立验证', () => {
  const target = buildRuntimeSkillTarget('/tmp/workspace', { id: 'review', runtimePath: 'team/review' }, 'codex');
  assert.equal(target, path.join('/tmp/workspace', '.agents', 'skills', 'team', 'review', 'SKILL.md'));
  assert.equal(hasManagedSkillMarker('---\nname: review\n---\n<!-- Generated by Buildr. Hash: x. Do not edit. -->\n'), true);
  assert.equal(hasManagedSkillMarker('---\nname: review\n---\nUser content\n'), false);

  const plan = buildAgentInstallPlanContent({
    id: 'remote-review',
    source: { kind: 'url', url: 'https://example.com/review' },
    resolved: { kind: 'skill-url', url: 'https://example.com/SKILL.md', version: '1.0.0' },
  });
  assert.match(plan, /Buildr Skill Install Plan: remote-review/);
  assert.match(plan, /https:\/\/example.com\/SKILL.md/);
  assert.match(plan, /skills add <id> --resolved-source/);
});
