import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  parseInstallClaudeCodeBuildrSkillArgs,
  parseRenderClaudeCodeArgs,
} from '../../tools/runtime/skills/arguments.mjs';
import { parseSkillsManifest } from '../../tools/runtime/skills/manifests.mjs';
import {
  normalizeRelativePath,
  resolveSkillScope,
} from '../../tools/runtime/skills/primitives.mjs';
import {
  applySkillRenderPlan,
  buildAgentInstallPlanContent,
  buildSkillRenderPlan,
  buildRuntimeSkillTarget,
  hasManagedSkillMarker,
} from '../../tools/runtime/skills/render-plan.mjs';
import { RUNTIME_ADAPTERS, SUPPORTED_AGENT_IDS, getRuntimeAdapter, skillDestinationRoot } from '../../tools/runtime/adapter-contract.mjs';
import { buildEffectiveSkillInventory, classifySkillCandidate } from '../../tools/runtime/skills/inventory.mjs';

test('render 参数解析拒绝未知和缺失参数', (t) => {
  t.mock.method(console, 'error', () => {});
  assert.deepEqual(parseRenderClaudeCodeArgs(['--scope', '.', '--target', 'tmp']), { scope: '.', target: 'tmp' });
  assert.deepEqual(parseInstallClaudeCodeBuildrSkillArgs(['--target', 'tmp']), { target: 'tmp' });
  assert.throws(() => parseRenderClaudeCodeArgs(['--scope', '.'], 'buildr render'), /Missing required arguments/);
  assert.throws(() => parseRenderClaudeCodeArgs(['--scope', '.', '--target', 'tmp', '--extra'], 'buildr render'), /Unknown argument/);
});

test('scope 和相对路径解析保持在 workspace 内', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-runtime-scope-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(root, 'projects', 'demo'), { recursive: true });

  assert.equal(normalizeRelativePath('./projects/demo'), path.join('projects', 'demo'));
  assert.throws(() => normalizeRelativePath('../outside'), /stay inside repository/);
  assert.deepEqual(resolveSkillScope(root, '.'), { scope: '.', organizationRoot: root, projectRoot: null });
  assert.equal(resolveSkillScope(root, 'projects/demo').projectRoot, path.join(root, 'projects', 'demo'));
  assert.throws(() => resolveSkillScope(root, 'services/api'), /Unsupported scope/);
});

test('Skills manifest parser 保留本地、远端和 runtime 字段', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-skills-manifest-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const manifest = path.join(root, 'manifest.yml');
  fs.writeFileSync(manifest, [
    'schemaVersion: buildr.skills/v1',
    'skills:',
    '  - id: local-review',
    '    path: local-review',
    '    enabled: true',
    '    runtimes: ["codex", "claude-code"]',
    '  - id: remote-review',
    '    source:',
    '      kind: url',
    '      url: https://example.com/review',
    '    resolved:',
    '      kind: skill-url',
    '      url: https://example.com/SKILL.md',
    '      integrity: sha256-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    '',
  ].join('\n'));

  const skills = parseSkillsManifest(manifest);
  assert.equal(skills.length, 2);
  assert.deepEqual(skills[0].runtimes, ['codex', 'claude-code']);
  assert.equal(skills[0].enabled, true);
  assert.equal(skills[1].source.kind, 'url');
  assert.equal(skills[1].resolved.kind, 'skill-url');
});

test('runtime target、managed marker 和 Agent install plan 可独立验证', () => {
  const target = buildRuntimeSkillTarget('/tmp/workspace', { id: 'review', runtimePath: 'team/review' }, 'codex');
  assert.equal(target, path.join('/tmp/workspace', '.agents', 'skills', 'team', 'review', 'SKILL.md'));
  assert.equal(hasManagedSkillMarker('---\nname: review\n---\n<!-- Generated by Buildr. Hash: x. Do not edit. -->\n'), true);
  assert.equal(hasManagedSkillMarker('---\nname: review\n---\nUser content\n'), false);

  const plan = buildAgentInstallPlanContent({
    id: 'remote-review',
    source: { kind: 'url', url: 'https://example.com/review' },
    resolved: { kind: 'skill-url', url: 'https://example.com/SKILL.md', version: '1.0.0' },
  });
  assert.match(plan, /Buildr Skill Install Plan: remote-review/);
  assert.match(plan, /https:\/\/example.com\/SKILL.md/);
  assert.match(plan, /skills add <id> --resolved-source/);
});

test('完整 Skill 目录跨 adapter 投射字节、权限、回执与 stale 清理', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-complete-skill-'));
  const sourceDir = path.join(root, 'source');
  const targetRoot = path.join(root, 'target');
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(sourceDir, 'assets'), { recursive: true });
  fs.mkdirSync(path.join(sourceDir, 'scripts'), { recursive: true });
  fs.mkdirSync(path.join(sourceDir, 'agents'), { recursive: true });
  fs.mkdirSync(targetRoot, { recursive: true });
  const sourceFile = path.join(sourceDir, 'SKILL.md');
  fs.writeFileSync(sourceFile, '---\nname: complete-demo\ndescription: complete demo\n---\n\n# Complete Demo\n');
  fs.writeFileSync(path.join(sourceDir, 'assets', 'sample.bin'), Buffer.from([0, 255, 16, 128]));
  fs.writeFileSync(path.join(sourceDir, 'scripts', 'run.sh'), '#!/bin/sh\necho demo\n');
  fs.chmodSync(path.join(sourceDir, 'scripts', 'run.sh'), 0o744);
  fs.writeFileSync(path.join(sourceDir, 'agents', 'openai.yaml'), 'interface:\n  display_name: Complete Demo\n');
  const skill = { id: 'complete-demo', sourceDir, sourceFile, origin: 'workspace', runtimePath: 'team/complete-demo', declaredScope: '.' };

  for (const adapterId of SUPPORTED_AGENT_IDS) {
    const projection = buildSkillRenderPlan(root, targetRoot, [skill], adapterId);
    const relativeTargets = projection.writes.map((item) => path.relative(targetRoot, item.targetFile).split(path.sep).join('/'));
    const runtimeRoot = getRuntimeAdapter(adapterId).traits.skills.root;
    for (const relative of ['SKILL.md', 'agents/openai.yaml', 'assets/sample.bin', 'scripts/run.sh']) {
      assert.ok(relativeTargets.includes(`${runtimeRoot}/skills/team/complete-demo/${relative}`), `${adapterId} missing ${relative}`);
    }
    assert.ok(relativeTargets.includes(`${runtimeRoot}/buildr/skill-projection-receipts/${adapterId}/team/complete-demo.json`));
  }

  const first = buildSkillRenderPlan(root, targetRoot, [skill], 'codex');
  applySkillRenderPlan(first, targetRoot);
  const runtimeDir = path.join(targetRoot, '.agents', 'skills', 'team', 'complete-demo');
  assert.deepEqual(fs.readFileSync(path.join(runtimeDir, 'assets', 'sample.bin')), Buffer.from([0, 255, 16, 128]));
  assert.equal((fs.statSync(path.join(runtimeDir, 'scripts', 'run.sh')).mode & 0o100) === 0o100, true);
  assert.match(fs.readFileSync(path.join(runtimeDir, 'SKILL.md'), 'utf8'), /Generated by Buildr/);

  const second = buildSkillRenderPlan(root, targetRoot, [skill], 'codex');
  assert.doesNotThrow(() => applySkillRenderPlan(second, targetRoot));
  fs.rmSync(path.join(sourceDir, 'assets', 'sample.bin'));
  const stale = buildSkillRenderPlan(root, targetRoot, [skill], 'codex');
  assert.equal(stale.removals.length, 1);
  applySkillRenderPlan(stale, targetRoot);
  assert.equal(fs.existsSync(path.join(runtimeDir, 'assets', 'sample.bin')), false);
});

test('完整 Skill 投射拒绝 source symlink 与已修改受管资源', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-complete-skill-conflict-'));
  const sourceDir = path.join(root, 'source');
  const targetRoot = path.join(root, 'target');
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(sourceDir, 'assets'), { recursive: true });
  fs.mkdirSync(targetRoot, { recursive: true });
  const sourceFile = path.join(sourceDir, 'SKILL.md');
  fs.writeFileSync(sourceFile, '---\nname: guarded-demo\ndescription: guarded demo\n---\n');
  fs.writeFileSync(path.join(sourceDir, 'assets', 'template.txt'), 'source\n');
  const skill = { id: 'guarded-demo', sourceDir, sourceFile, origin: 'workspace', runtimePath: 'guarded-demo', declaredScope: '.' };
  applySkillRenderPlan(buildSkillRenderPlan(root, targetRoot, [skill], 'codex'), targetRoot);
  const runtimeAsset = path.join(targetRoot, '.agents', 'skills', 'guarded-demo', 'assets', 'template.txt');
  fs.writeFileSync(runtimeAsset, 'user edit\n');
  fs.writeFileSync(path.join(sourceDir, 'assets', 'template.txt'), 'new source\n');
  assert.throws(() => applySkillRenderPlan(buildSkillRenderPlan(root, targetRoot, [skill], 'codex'), targetRoot), /no files were changed/);
  assert.equal(fs.readFileSync(runtimeAsset, 'utf8'), 'user edit\n');

  fs.rmSync(path.join(sourceDir, 'assets', 'template.txt'));
  fs.symlinkSync(sourceFile, path.join(sourceDir, 'assets', 'linked.md'));
  assert.throws(() => buildSkillRenderPlan(root, targetRoot, [skill], 'codex'), /must not contain symbolic links/);
});

test('adapter 明确声明 user/workspace destination 与 partial inventory evidence', () => {
  for (const adapter of Object.values(RUNTIME_ADAPTERS)) {
    const destinations = adapter.traits.skills.destinations;
    assert.equal(destinations.workspace.supported, true);
    assert.equal(destinations.user.supported, true);
    assert.equal(destinations.discovery.evidence, 'partial');
    assert.ok(skillDestinationRoot(adapter, 'workspace', '/tmp/workspace').endsWith(adapter.traits.skills.root));
  }
});

test('effective inventory 只读汇总外部 Skill 并稳定分类', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-skill-inventory-'));
  const userHome = path.join(root, 'user');
  const skillDir = path.join(root, '.agents', 'skills', 'demo');
  const unrelatedDir = path.join(root, '.agents', 'skills', 'unrelated');
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(skillDir, { recursive: true });
  fs.mkdirSync(unrelatedDir, { recursive: true });
  fs.writeFileSync(path.join(skillDir, 'SKILL.md'), '---\nname: demo\ndescription: demo\n---\nbody\n');
  fs.writeFileSync(path.join(unrelatedDir, 'SKILL.md'), '---\nname: unrelated\ndescription: unrelated\n---\nbody\n');
  const before = fs.statSync(path.join(skillDir, 'SKILL.md')).mtimeMs;
  const inventory = buildEffectiveSkillInventory({ adapterId: 'codex', workspaceRoot: root, userHome, candidateIds: ['demo'] });
  assert.equal(inventory.entries.length, 1);
  assert.equal(inventory.entries.some((entry) => entry.skillId === 'unrelated'), false);
  assert.equal(inventory.entries[0].sourceCategory, 'external-filesystem');
  const equivalent = classifySkillCandidate({ skillId: 'demo', assetIdentity: 'workspace:x:skill:demo', renderDigest: inventory.entries[0].renderDigest }, inventory, 'workspace');
  assert.equal(equivalent.status, 'equivalent_external');
  assert.equal(equivalent.blocking, true);
  const conflict = classifySkillCandidate({ skillId: 'demo', assetIdentity: 'workspace:x:skill:demo', renderDigest: `sha256-${'0'.repeat(64)}` }, inventory, 'workspace');
  assert.equal(conflict.status, 'name_conflict');
  const absent = classifySkillCandidate({ skillId: 'other', assetIdentity: 'workspace:x:skill:other', renderDigest: `sha256-${'0'.repeat(64)}` }, inventory, 'workspace');
  assert.equal(absent.status, 'visibility_partial');
  assert.equal(fs.statSync(path.join(skillDir, 'SKILL.md')).mtimeMs, before);
});

test('Skill conflict classifier 覆盖受管、外部、跨 owner 与 user satisfaction 状态', () => {
  const candidate = { skillId: 'demo', assetIdentity: 'asset:demo', sourceWorkspaceId: 'workspace:a', renderDigest: `sha256-${'1'.repeat(64)}` };
  const classify = (entries, destination = 'workspace', evidence = 'complete') => classifySkillCandidate(candidate, { entries, evidence }, destination).status;
  assert.equal(classify([]), 'absent');
  assert.equal(classify([], 'workspace', 'partial'), 'visibility_partial');
  assert.equal(classify([{ skillId: 'demo', destination: 'workspace', assetIdentity: 'asset:demo', renderDigest: candidate.renderDigest, receipt: {} }]), 'already_projected');
  assert.equal(classify([{ skillId: 'demo', destination: 'workspace', assetIdentity: 'asset:demo', renderDigest: `sha256-${'2'.repeat(64)}`, receipt: {} }]), 'update');
  assert.equal(classify([{ skillId: 'demo', destination: 'workspace', assetIdentity: null, renderDigest: candidate.renderDigest, receipt: null }]), 'equivalent_external');
  assert.equal(classify([{ skillId: 'demo', destination: 'workspace', assetIdentity: null, renderDigest: `sha256-${'2'.repeat(64)}`, receipt: null }]), 'name_conflict');
  assert.equal(classify([{ skillId: 'demo', destination: 'workspace', assetIdentity: 'asset:other', renderDigest: candidate.renderDigest, receipt: { schemaVersion: 'buildr.skill-projection/v2' } }]), 'foreign_owner');
  assert.equal(classify([{ skillId: 'demo', destination: 'user', assetIdentity: 'asset:demo', sourceWorkspaceId: 'workspace:b', renderDigest: `sha256-${'2'.repeat(64)}`, receipt: { schemaVersion: 'buildr.skill-projection/v2' } }], 'user'), 'foreign_owner');
  assert.equal(classify([{ skillId: 'demo', destination: 'user', assetIdentity: 'asset:demo', sourceWorkspaceId: 'workspace:a', renderDigest: `sha256-${'2'.repeat(64)}`, receipt: { schemaVersion: 'buildr.skill-projection/v2' } }], 'user'), 'update');
  assert.equal(classify([{ skillId: 'demo', destination: 'user', assetIdentity: 'asset:demo', renderDigest: candidate.renderDigest, receipt: { schemaVersion: 'buildr.skill-projection/v2' } }]), 'satisfied_by_user');
});
